#!/usr/bin/perl 
{
    foreach $inFileName (@ARGV) {
	open INTEXTFILE , $inFileName;
	open OUTTEXTFILE, ">". $inFileName . ".con";
        binmode OUTTEXTFILE;
        binmode INTEXTFILE;
	@textFile = <INTEXTFILE>;
	foreach $textline (@textFile) {
                $textline =~ s/\x0d\x0a/\x0a/g;
		$textline =~ s/\x0d/\x0a/g;
		$textline =~ s/\x0a/\x0d\x0a/g;
		print OUTTEXTFILE $textline ;
	};
	close (INTEXTFILE);
	close (OUTTEXTFILE);
	rename($inFileName,$inFileName . ".mac");
	rename($inFileName . ".con",$inFileName);
	unlink($inFileName . ".mac");
    }
}

