#!/usr/bin/env bash

ASG_NAME="${1:-backup-app-qa0}"

instance_ips=$(asg_ip_addrs "$ASG_NAME")

date_suffix=$(date +%Y%m%d_%H%M%S)
full_file_name="/etc/backup/configatron.d/configatron.rb"
dir_name=$(dirname  ${full_file_name})
file_name=$(basename ${full_file_name})
file_name_base=${file_name%.*}
file_name_ext=${file_name##*.}
full_file_name_copy="${dir_name}/${file_name_base}-${date_suffix}.${file_name_ext}"

for instance_ip in $instance_ips
do
  ssh -t $instance_ip <<EOF
    echo "set -x" > /tmp/bash.tmp
    echo "cp $full_file_name $full_file_name_copy" >> /tmp/bash.tmp
    echo "sed s/^configatron.db.hosts.*$/configatron.db.hosts\ \=\ [\\\\\"cassandra-backup-core-ec2-multinode-seed.staging.lkt.is\\\\\"]/g <$full_file_name_copy >$full_file_name" >> /tmp/bash.tmp
    echo "service backup restart" >> /tmp/bash.tmp
    #cat /tmp/bash.tmp
    sudo bash /tmp/bash.tmp
EOF
sleep 15
done

