#!/usr/bin/env ruby

# Must be jruby 
#  jruby-openssl >= 0.9.5
#  octocrypt = 0.3.17

require 'openssl'
require 'octocrypt'


keys = [' .... ', ' .... '] # Backup encryption keys
keys = ["u9bF==", "VWj=="]

data = "Some data to encrypt"

# initializers/octocrypt
# Octocrypt.configure(
#     Octocrypt::Constants::MASTER_KEY_HMAC_PHASE, # Octocrypt::Constants::NO_ENCRYPTION_PHASE
#     'AES-256-CFB',
#     configatron.encryption.secrets.map { |key| Base64.decode64(key) }
# )
Octocrypt.configure(
    Octocrypt::Constants::MASTER_KEY_HMAC_PHASE, # Octocrypt::Constants::NO_ENCRYPTION_PHASE
    'AES-256-CFB',
    keys.map { |key| Base64.decode64(key) }
)


# Backup::AwsBaseWriteChannel  @encrypt = Octocrypt::Encryptor.new
encrypter = Octocrypt::Encryptor.new

encrypted_data = ''

# Backup::AwsBaseWriteChannel encrypted = @encrypt.update (@zstream ? @zstream.compress(data) : data)
encrypted_data << encrypter.update(data)
# Backup::AwsBaseWriteChannel encrypted = @encrypt.final
encrypted_data <<  encrypter.final
# Backup::AwsBaseWriteChannel @scheme = @encrypt.scheme
scheme = encrypter.scheme

puts scheme

