#!/usr/bin/env ruby

# Must be jruby 
#  jruby-openssl >= 0.9.5
#  octocrypt = 0.3.17


require 'openssl'
require 'octocrypt'


keys = [' .... ', ' .... '] # Backup encryption keys
keys = ["u9bFaca", "VWj22LkgqQ"]

# initializers/octocrypt
# Octocrypt.configure(
#     Octocrypt::Constants::MASTER_KEY_HMAC_PHASE, # Octocrypt::Constants::NO_ENCRYPTION_PHASE
#     'AES-256-CFB',
#     configatron.encryption.secrets.map { |key| Base64.decode64(key) }
# )
Octocrypt.configure(
    Octocrypt::Constants::MASTER_KEY_HMAC_PHASE, # Octocrypt::Constants::NO_ENCRYPTION_PHASE
    'AES-256-CFB',
    keys.map { |key| Base64.decode64(key) }
)

data = "Some data to encrypt"


# Backup::AwsBaseWriteChannel  @encrypt = Octocrypt::Encryptor.new
encrypter = Octocrypt::Encryptor.new

encrypted_data = ''

# Backup::AwsBaseWriteChannel encrypted = @encrypt.update (@zstream ? @zstream.compress(data) : data)
encrypted_data << encrypter.update(data)
# Backup::AwsBaseWriteChannel encrypted = @encrypt.final
encrypted_data <<  encrypter.final
# Backup::AwsBaseWriteChannel @scheme = @encrypt.scheme
scheme = encrypter.scheme

puts scheme

# octocypt gem
#original = Octocrypt.decrypt(encrypted, scheme)
decrypted_data = Octocrypt.decrypt(encrypted_data, scheme)

puts decrypted_data


input_file = File.open("/Users/tflynn/tmp/3bba0860-818c-441a-86c2-e3e294b2ce14", "rb") # File containing  compressed call log
encrypted_data = input_file.read
puts "encrypted_data.length #{encrypted_data.length}"
input_file.close

scheme = "AES-256-CFB:2:1:DVcqP8CZE_2w8FiA5koqMw==:yyyif2YU40eUJ7Gr9UBdC9-cZ3NL2tIwtmziZDu46fE="

decrypter = Octocrypt::Decryptor.new(scheme)
decrypted_data  = ""
decrypted_data << decrypter.update(encrypted_data)
decrypted_data << decrypter.final

puts "decrypted_data.length #{decrypted_data.length}"
output_file = File.open("3bba0860-818c-441a-86c2-e3e294b2ce14.gz",'wb')
output_file.write decrypted_data
output_file.close

