#!/usr/bin/env ruby

require 'time'

daylight_time_us = true
daylight_time_ukr = true
bos_offset = (daylight_time_us ? 4 : 5) * 60 * 60
sf_offset = (daylight_time_us ? 7 : 8) * 60 * 60
ukr_offset = (daylight_time_ukr ? -3 : -2 ) * 60 * 60


now = Time.now.utc
mod_8601 = "%Y-%m-%dT%H-%M-%SZ"
local_no_tz = "%Y-%m-%dT%H:%M:%SZ"

now_bos = now - bos_offset
now_sf = now - sf_offset
now_ukr = now - ukr_offset

puts "#{now.iso8601} #{now.strftime(mod_8601)} BOS #{now_bos.strftime(local_no_tz)} SF #{now_sf.strftime(local_no_tz)} UKR #{now_ukr.strftime(local_no_tz)}"

