#!/usr/bin/env bash

INPUT_FILE_NAME=$1
OUTPUT_FILE_NAME="${1}.out"

rm -f "${OUTPUT_FILE_NAME}"
cat "$INPUT_FILE_NAME" | sed -e 's/\\/\\\\/g' | awk '{printf "%s\\n",$0}' | sed 's/"/\\"/g' > ${OUTPUT_FILE_NAME}

echo "Output file ${OUTPUT_FILE_NAME}"
