#!/usr/bin/env python3

import sys
import os
from os import path

if len(sys.argv) != 2 :
	sys.exit(1)

file_path = sys.argv[1]
dir_name = path.dirname(file_path)
base_file_name = path.basename(file_path)
base_file_name_no_ext = path.splitext(base_file_name)[0]
base_file_name_ext = path.splitext(base_file_name)[1][1:]

print("{0},{1},{2},{3},{4}".format(file_path, dir_name, base_file_name, base_file_name_no_ext, base_file_name_ext))
