#!/usr/bin/env bash

#set -x

# Find all instances with a given name
# Can't use the 'Name' tag directly
# "Name" tag search only supported on default VPC or on EC2 Classic instances.

DEFAULT_NAME="locate-app-stage"

if [ -z $1 ]; then
  name=${DEFAULT_NAME}
else
  name="${1}"
fi

security_group=$(aws ec2 describe-security-groups --filters Name=group-name,Values=${name} | jq -r ".SecurityGroups[] | .GroupId")

instanceIDs=$(aws ec2 describe-instances --filters Name=instance.group-id,Values=${security_group} | jq -r ".Reservations[] | .Instances[] | .InstanceId")

for instanceID in ${instanceIDs}
do
  echo $instanceID
done

