#!/usr/bin/env bash

proc_name=$1
if [ "$OSTYPE" == "darwin16" ]; then
  pid=$(ps alx | grep -v grep | grep -i $proc_name | awk '{print $2}')
else
  pid=$(ps alx | grep -v grep | grep -i $proc_name | awk '{print $3}')
fi

echo $pid

