#!/bin/tcsh

# Tag a OneID file in svne
#echo hello
#echo svn copy file:///Users/tracy/Projects/svnrepository/Docs/OneID/trunk file:///Users/tracy/Projects/svnrepository/Docs/OneID/tags/$1 -m\"$2\"
svn copy file:///Users/tracy/Projects/svnrepository/Docs/OneID/trunk file:///Users/tracy/Projects/svnrepository/Docs/OneID/tags/$1 -m$1

