#!/usr/bin/env ruby

#
# Script to generate memorable passwords consisting of words, numbers and special characters


if ARGV.size != 1
  puts "Usage: $0 <length> "
  exit 1
end
password_length = ARGV[0].to_i

# Adapted from https://github.com/jvdl/CorrectHorseBatteryStaple.git

raw_words = <<WORDS_BOUNDARY
the,be,of,and,a,to,in,he,have,it,that,for,they,I,with,as,not,on,she,at,by,this,we,you,do,but,from,or,which,one,would,all,
will,there,say,who,make,when,can,more,if,no,man,out,other,so,what,time,up,go,about,than,into,could,state,only,new,year,so
me,take,come,these,know,see,use,get,like,then,first,any,work,now,may,such,give,over,think,most,even,find,day,also,after,w
ay,many,must,look,before,great,back,through,long,where,much,should,well,people,down,own,just,because,good,each,those,feel
,seem,how,high,too,place,little,world,very,still,nation,hand,old,life,tell,write,become,here,show,house,both,between,need
,mean,call,develop,under,last,right,move,thing,general,school,never,same,another,begin,while,number,part,turn,real,leave,
might,want,point,form,off,child,few,small,since,against,ask,late,home,interest,large,person,end,open,public,follow,during
,present,without,again,hold,govern,around,possible,head,consider,word,program,problem,however,lead,system,set,order,eye,p
lan,run,keep,face,fact,group,play,stand,increase,early,course,change,help,line,city,put,close,case,force,meet,once,water,
upon,war,build,hear,light,unite,live,every,country,bring,center,let,side,try,provide,continue,name,certain,power,pay,resu
lt,question,study,woman,member,until,far,night,always,service,away,report,something,company,week,church,toward,start,soci
al,room,figure,nature,though,young,less,enough,almost,read,include,president,nothing,yet,better,big,boy,cost,business,val
ue,second,why,clear,expect,family,complete,act,sense,mind,experience,art,next,near,direct,car,law,industry,important,girl
,god,several,matter,usual,rather,per,often,kind,among,white,reason,action,return,foot,care,simple,within,love,human,along
,appear,doctor,believe,speak,active,student,month,drive,concern,best,door,hope,example,inform,body,ever,least,probable,un
derstand,reach,effect,different,idea,whole,control,condition,field,pass,fall,note,special,talk,particular,today,measure,w
alk,teach,low,hour,type,carry,rate,remain,full,street,easy,although,record,sit,determine,level,local,sure,receive,thus,mo
ment,spirit,train,college,religion,perhaps,music,grow,free,cause,serve,age,book,board,recent,sound,office,cut,step,class,
true,history,position,above,strong,friend,necessary,add,court,deal,tax,support,party,whether,either,land,material,happen,
education,death,agree,arm,mother,across,quite,anything,town,past,view,society,manage,answer,break,organize,half,fire,lose
,money,stop,actual,already,effort,wait,department,able,political,learn,voice,air,together,shall,cover,common,subject,draw
,short,wife,treat,limit,road,letter,color,behind,produce,send,term,total,university,rise,century,success,minute,remember,
purpose,test,fight,watch,situation,south,ago,difference,stage,father,table,rest,bear,entire,market,prepare,explain,offer,
plant,charge,ground,west,picture,hard,front,lie,modern,dark,surface,rule,regard,dance,peace,observe,future,wall,farm,clai
m,firm,operation,further,pressure,property,morning,amount,top,outside,piece,sometimes,beauty,trade,fear,demand,wonder,lis
t,accept,judge,paint,mile,soon,responsible,allow,secretary,heart,union,slow,island,enter,drink,story,experiment,stay,pape
r,space,apply,decide,share,desire,spend,sign,therefore,various,visit,supply,officer,doubt,private,immediate,wish,contain,
feed,raise,describe,ready,horse,son,exist,north,suggest,station,effective,food,deep,wide,alone,character,english,happy,cr
itic,unit,product,respect,drop,nor,fill,cold,represent,sudden,basic,kill,fine,trouble,mark,single,press,heavy,attempt,ori
gin,standard,everything,committee,moral,black,red,bad,earth,accord,else,mere,die,remark,basis,except,equal,east,event,emp
loy,defense,smile,river,improve,game,detail,account,cent,sort,reduce,club,buy,attention,ship,decision,wear,inside,win,sup
pose,ride,operate,realize,sale,choose,park,square,vote,price,district,dead,foreign,window,beyond,direction,strike,instead
,trial,practice,catch,opportunity,likely,recognize,permit,serious,attack,floor,association,spring,lot,stock,lack,hair,sci
ence,relation,profession,pattern,quick,medical,influence,occasion,machine,compare,husband,blue,international,fair,especia
lly,indeed,imagine,surprise,average,official,temperature,difficult,sing,hit,tree,race,police,touch,relative,throw,quality
,former,pull,chance,prove,argue,settle,growth,date,heat,save,performance,count,production,listen,main,pick,size,cool,army
,patient,combine,summer,hall,slight,command,enjoy,length,proper,express,health,chief,evening,store,language,degree,lay,cu
rrent,gun,dog,hotel,strange,separate,boat,fail,clean,dress,anyone,gain,pain,object,knowledge,depend,relate,below,dollar,a
dvance,shape,arrange,population,yes,sell,mention,dry,check,poet,sleep,join,hot,bed,electric,dream,due,season,manner,fit,l
eft,progress,neither,strength,notice,finish,opinion,bill,western,truth,wrong,travel,suit,bank,exact,honor,brother,quiet,m
arry,corner,handle,danger,hospital,pool,promise,blood,shoot,scene,literature,arrive,film,base,freedom,bar,maybe,hang,suff
er,manufacture,frequent,rock,loss,burn,sun,audience,essential,glass,prevent,poem,poor,inch,song,skill,post,popular,radio,
animal,conscious,worth,eat,election,faith,wave,murder,model,forget,extend,edge,distance,memory,recommend,division,staff,l
eg,discussion,address,fly,dependent,ball,shake,frame,extreme,engineer,thick,comfort,latter,camp,oil,discover,examine,diff
iculty,tooth,middle,choice,refer,enemy,practical,marriage,bridge,declare,lady,cross,daily,afternoon,attend,director,balan
ce,wash,capital,speed,block,citizen,mouth,hill,green,please,motor,agency,encourage,governor,worry,affair,shoulder,bright,
mass,sample,pretty,repeat,roll,push,trip,council,clothe,parent,forward,sharp,straight,gas,weight,discuss,fix,load,master,
whatever,round,rapid,laugh,finger,spot,propose,shop,broad,replace,reply,extent,lock,employee,ahead,sight,spread,wind,appr
ove,destroy,none,pound,fame,importance,reflect,advantage,match,regular,wage,refuse,existence,hardly,perform,title,tend,ex
ercise,thin,coat,bit,mountain,youth,behavior,newspaper,secret,ability,sea,soft,justice,reasonable,circle,solid,page,weapo
n,fast,representative,search,pure,escape,crowd,stick,telephone,avoid,garden,favor,news,unless,dinner,someone,signal,yard,
ideal,warm,miss,shelter,soldier,article,cry,captain,familiar,seat,guest,weak,excite,king,everyone,wine,hole,duty,beat,per
fect,bottom,compose,battle,expense,cattle,flow,kitchen,dust,bottle,admit,tear,tire,expression,exception,application,belon
g,rich,failure,struggle,instrument,variety,narrow,theater,collection,rain,review,preserve,leadership,clay,daughter,fellow
,swing,thank,library,fat,reserve,tour,nice,warn,ring,bitter,chair,yesterday,scientific,flower,wheel,solution,aim,gather,i
nvite,moreover,fresh,forest,winter,box,belief,ordinary,impossible,print,gray,taste,lip,speech,reference,stain,connection,
otherwise,stretch,knife,village,blow,mistake,sweet,shout,divide,guard,worse,exchange,rare,commercial,request,appoint,agen
t,dependence,bird,wild,motion,guess,neighbor,seed,fashion,loan,correct,plain,mail,retire,opposite,prefer,safe,evil,double
,wood,empty,baby,advise,content,sport,lift,literary,curious,tie,flat,message,neck,hate,dirt,delight,trust,nobody,valley,t
ool,presence,cook,railroad,minister,coffee,brush,beside,collect,guide,luck,profit,lord,everybody,prison,cloud,slave,chair
man,soil,distinguish,introduce,urge,blind,arise,upper,curve,membership,key,entertain,soul,neighborhood,friendly,pair,ston
e,lean,protect,advertise,mystery,welcome,knee,jump,snake,stream,avenue,brown,disease,hat,excellent,formal,snow,sheet,some
how,unity,sky,rough,smooth,weather,steady,threaten,depth,oppose,deliver,ancient,pray,adopt,birth,appearance,universe,busy
,hurry,coast,forth,smell,furnish,female,hide,wire,proposal,ought,victory,quarter,engine,customer,waste,fool,intend,intent
ion,desk,politics,passage,lawyer,root,climb,metal,gradual,hunt,protection,satisfy,roof,branch,pleasure,witness,loose,nose
,mine,band,aside,risk,tomorrow,remind,ear,fish,shore,operator,civilize,being,silent,screen,bind,earn,pack,colony,besides,
slip,cousin,scale,relief,explore,stem,brain,musician,defend,bend,somebody,shadow,mix,smoke,description,fruit,guilt,yield,
sensitive,salt,pale,sweep,completion,throat,agriculture,admire,gentle,dozen,particle,pleasant,bay,cup,competition,moon,te
rrible,strip,mechanic,shock,conversation,angle,tall,plenty,star,yellow,sick,thorough,absolute,succeed,surround,proud,dear
,card,lake,breath,afraid,silence,onto,shoe,somewhere,chain,slide,copy,machinery,wake,severe,pocket,bone,honest,freeze,dic
tionary,calm,swim,ice,male,skin,crack,rush,wet,meat,commerce,joint,gift,host,suspect,path,uncle,afford,instant,satisfacto
ry,height,track,confidence,grass,suggestion,favorite,breakfast,apart,chest,entrance,march,sink,northern,iron,alive,ill,ba
g,disturb,native,bedroom,violent,beneath,pause,tough,substance,threat,charm,absence,factory,spite,meal,universal,accident
,highway,sentence,liberty,wise,noise,discovery,tube,flash,twist,fence,childhood,joy,sister,sad,efficiency,disappear,defea
t,extensive,rent,comparison,possess,grace,flesh,liquid,scientist,ease,heaven,milk,sympathy,rank,restaurant,frequency,angr
y,shade,accuse,necessity,knock,loud,permanent,row,lovely,confuse,gold,frighten,solve,grave,salary,photograph,advice,abroa
d,wound,virtue,dare,queen,extra,attract,numerous,pink,gate,expensive,shut,chicken,forgive,holy,wooden,prompt,crime,sorry,
republic,anger,visitor,pile,violence,steel,wing,stair,partner,delay,gentleman,pour,confusion,damage,kick,safety,burst,net
work,resistance,screw,pride,till,hire,verb,preach,clerk,everywhere,anyway,fan,connect,egg,efficient,grain,calculate,drag,
opposition,worship,arrest,discipline,string,harbor,camera,mechanism,cow,grand,funny,insurance,reduction,strict,lesson,tig
ht,sand,plate,qualify,elsewhere,mad,interference,pupil,fold,royal,valuable,whisper,anybody,hurt,excess,quantity,fun,mud,e
xtension,recognition,kiss,crop,sail,attractive,habit,relieve,wisdom,persuade,certainty,cloth,eager,deserve,sympathetic,cu
re,trap,puzzle,powder,raw,mankind,glad,blame,whenever,anxiety,bus,tremble,sacred,fortunate,glory,golden,neat,weekend,trea
sury,overcome,cat,sacrifice,complain,elect,roar,sake,temple,self,compete,nurse,stuff,stomach,peculiar,repair,storm,ton,de
sert,allowance,servant,hunger,conscience,bread,crash,tip,strengthen,proof,generous,sir,tonight,whip,tongue,mill,merchant,
coal,ruin,introduction,courage,actor,belt,stir,package,punish,reflection,breathe,anywhere,amuse,dull,fate,net,fellowship,
fault,furniture,beam,pencil,border,disappoint,flame,joke,bless,corn,shell,tempt,supper,destruction,dive,anxious,shine,che
ap,dish,distant,greet,flood,excuse,insect,ocean,ceremony,decrease,prize,harm,insure,verse,pot,sincere,cotton,leaf,rub,med
icine,stroke,bite,lung,lonely,admission,stupid,scratch,composition,broadcast,drum,resist,neglect,absent,passenger,adventu
re,beg,pipe,beard,bold,meanwhile,devil,cheer,nut,split,melt,swear,sugar,bury,wipe,faint,creature,tail,wealth,earnest,tran
slate,suspicion,noble,inquiry,journey,hesitate,extraordinary,borrow,owe,funeral,ambition,mixture,slope,criminal,seldom,ma
p,spin,praise,spare,plow,telegraph,barrel,straighten,scarce,lunch,slavery,creep,sweat,gay,stiff,brave,seize,convenient,ho
rizon,moderate,complicate,dig,curse,weigh,priest,excessive,quarrel,widow,modest,dine,politician,custom,educate,salesman,n
ail,tap,eastern,possession,satisfaction,behave,mercy,scatter,objection,silver,tent,saddle,wrap,nest,grind,spell,plaster,a
rch,swell,friendship,bath,bundle,grateful,crown,boundary,nowhere,asleep,clock,boil,altogether,lend,holiday,precious,wande
r,ugly,reputation,ticket,pretend,dismiss,delicate,despair,awake,tea,FALSE,fortune,cap,thread,haste,bare,shirt,bargain,lea
ther,rail,butter,dot,inquire,warmth,decisive,vessel,pity,steam,pin,bound,companion,toe,reward,forbid,wherever,tower,bathe
,lodge,swallow,multiply,bow,kingdom,garage,permission,pump,prevention,urgent,aunt,zero,idle,fever,christmas,regret,jaw,so
ap,pronounce,empire,bowl,outline,organ,imitation,caution,mineral,disagree,blade,trick,treasure,immense,convenience,disapp
rove,destructive,fork,noon,ownership,tune,polish,poison,shame,loyalty,cottage,astonish,shave,feather,sauce,lid,debt,fade,
confess,classification,descend,cape,mild,clever,envelope,invention,sheep,splendid,stamp,float,brick,rice,businessman,back
ward,qualification,artificial,attraction,lamp,curl,shower,elder,bunch,bell,steer,flavor,spit,rob,cream,interrupt,pen,weav
e,orange,rescue,crush,humble,fancy,decay,polite,tribe,bleed,coin,fond,autumn,classify,omit,loyal,needle,lessen,complaint,
pad,steep,skirt,curtain,calculation,laughter,solemn,grease,interfere,explode,fasten,flag,resign,postpone,patience,boast,r
ope,envy,airplane,rid,shield,veil,kneel,tray,explosive,brass,taxi,wax,duck,button,invent,remedy,bush,thunder,weaken,pover
ty,scrape,arrow,tender,cruel,soften,mouse,hay,anyhow,alike,circular,juice,shelf,bake,hatred,cautious,basket,wreck,width,c
onfident,log,heap,suck,ladder,gap,obey,hut,axe,translation,collar,delivery,reproduce,confession,pan,prejudice,voyage,toba
cco,simplicity,paste,cake,elephant,ribbon,harvest,ashamed,cave,customary,thief,damp,sew,rust,separation,waiter,pet,straw,
upset,towel,refresh,essence,fur,ambitious,defendant,daylight,dip,suspicious,imaginary,ash,carriage,educator,saw,stove,rub
ber,rug,misery,awkward,rival,roast,deed,preference,explosion,theatrical,cultivate,collector,miserable,wrist,rabbit,accust
om,tide,insult,thumb,lump,annoy,toy,heal,shallow,repetition,soup,whistle,scenery,apple,offense,cork,ripe,temper,sore,pinc
h,diamond,razor,imaginative,hook,copper,landlord,influential,rot,hollow,enclose,harden,wicked,stiffen,silk,upright,selfis
h,stripe,pig,inward,excellence,rake,purple,hasten,shorten,applause,ache,apology,knot,nephew,cushion,drown,nursery,pint,fi
erce,imitate,aloud,gaiety,robbery,tighten,perfection,scorn,whoever,trunk,wool,sailor,competitor,moonlight,deer,bean,every
day,drawer,disregard,nowadays,patriotic,tin,penny,cage,pardon,lately,offend,coarse,spoil,horizontal,sting,ditch,librarian
,meantime,cough,deaf,sword,messenger,vain,castle,elastic,comb,rod,widen,sorrow,inventor,cliff,umbrella,interruption,merry
,gallon,conquest,headache,tailor,bucket,scent,signature,cart,darken,sometime,applaud,underneath,hello,pretense,descent,co
nquer,framework,confidential,adoption,disgust,waist,momentary,receipt,pearl,ray,lazy,limb,grammatical,beast,monkey,jewel,
persuasion,obedience,sock,vowel,hammer,inn,chimney,dissatisfaction,annoyance,ornament,honesty,outward,sharpen,handkerchie
f,greed,heavenly,thirst,niece,spill,loaf,wheat,worm,secrecy,rude,heighten,flatten,loosen,cheese,rivalry,royalty,disconten
t,complication,fright,indoor,flour,actress,congratulation,ounce,fry,everlasting,goat,ink,disappearance,reproduction,thick
en,avoidance,spoon,strap,deceive,lengthen,revenge,correction,descendant,hesitation,spade,basin,weed,omission,old-fashione
d,bicycle,breadth,photography,coward,mat,rejoice,cheat,congratulate,discomfort,enclosure,attentive,paw,overflow,dissatisf
y,multiplication,whichever,tidy,bribe,mend,stocking,feast,nuisance,thorn,tame,inclusive,homemade,handwriting,chalk,sour,s
lippery,procession,ripen,jealous,jealousy,liar,homecoming,barber,whiten,berry,lighten,pigeon,hinder,bravery,baggage,noun,
amongst,grammar,cultivation,companionship,rubbish,modesty,woolen,deepen,pastry,cupboard,quart,canal,notebook,deceit,parce
l,brighten,moderation,punctual,hurrah,lipstick,uppermost,fatten,conqueror,hindrance,cowardice,obedient,saucer,madden,scol
d,weekday,rotten,disrespect,widower,deafen,donkey,businesslike,motherhood,sadden,handshake,calculator,headdress,scissors,
translator,possessor,shilling,redden,motherly,whose,cultivator,whom,homework,electrician,oar,bribery,sweeten,sow,pronunci
ation,beak,plural

WORDS_BOUNDARY

$WORD_LIST = raw_words.split("\n").each{|l| l.chomp}.join('').split(',')

$DIGITS = [0,1,2,3,4,5,6,7,8,9]
$TOTAL_DIGITS = 4
$SPECIAL_CHARACTERS = '=*&^%$#!'.split('')
$TOTAL_SPECIAL_CHARACTERS = 1
$INITIAL_CAPS = 1

def get_random_elements(num_random, elements_list)
  result = []
  total_elements = elements_list.size
  1.upto(num_random) do |i|
    random_index = rand(total_elements)
    result << elements_list[random_index]
  end
  result
end

def init_cap(s)
  s.slice(0,1).capitalize + s.slice(1..-1)
end

def generate_password(password_length = 20) 
  words_pool = get_random_elements(password_length,$WORD_LIST)
  digits_pool = get_random_elements($TOTAL_DIGITS,$DIGITS)
  separators_pool = ['']
  
  raw_password = ""
  last_separator = nil
  while raw_password.length <= password_length
    raw_password << init_cap(get_random_elements(1,$WORD_LIST)[0])
    break if raw_password.length > password_length
    last_separator = get_random_elements(1,separators_pool)[0]
    raw_password << last_separator
    break if raw_password.length > password_length
    # raw_password << get_random_elements(1,$DIGITS)[0].to_s
    # break if raw_password.length > password_length
    # last_separator = get_random_elements(1,separators_pool)[0]
    # raw_password << last_separator
  end
  if raw_password[-1, 1] != last_separator
    last_separator = get_random_elements(1,separators_pool)[0]
    raw_password << last_separator
  end
  raw_password << get_random_elements($TOTAL_DIGITS,$DIGITS).each{|d| d.to_s}.join('')       
  final_password = raw_password + get_random_elements(1,$SPECIAL_CHARACTERS)[0]
  final_password
end

puts generate_password(password_length)


