#!/usr/bin/env ruby

require "digest/sha1"

if (ARGV.size != 2) 
  puts "Usage: password_hash <password> <salt>"
  exit 1
end

password = ARGV[0]
salt = ARGV[1]

password_and_salt = "#{password.downcase}#{salt}"
password_hash =  Digest::SHA1.hexdigest(password_and_salt)

puts password_hash

