#!/usr/bin/env python3

import sys
import os
from textwrap import dedent
from subprocess import Popen, PIPE, STDOUT


def print_header(path):
    msg = dedent("""

    ========

    path {0}
    packages 

    """).format(path)
    print(msg)
    return


def print_footer():
    msg = dedent("""
    ========
    """)
    print(msg)
    return


for path in sys.path:
    if os.path.exists(path):
        print_header(path)
        cmd = ["ls -1"]
        p = Popen(cmd,
                  cwd=path,
                  shell=True,
                  executable='/bin/bash',
                  stdin=PIPE,
                  stdout=PIPE,
                  stderr=STDOUT,
                  close_fds=True
                 )
        for line in p.stdout:
            line = line.decode("utf-8").strip()
            print(line)

        print_footer()
