#!/usr/bin/env python3

import sys
import os
from os import path

if len(sys.argv) == 1:
    cwd = os.getcwd()
    cwd_basename = path.basename(cwd)
    package_prefix = cwd_basename
elif len(sys.argv) == 2:
    package_prefix = sys.argv[1]

#print("package_prefix {0}".format(package_prefix))

ps=sys.path

matching_paths = []

for p in ps:
    if path.exists(p):
        cmd="find {0} -iname \*{1}\*".format(p,package_prefix)
        #print(cmd)
        find_out=os.popen(cmd).read().strip()
        #print(find_out)
        if find_out:
            matches = find_out.split()
            for match in matches:
                if match not in matching_paths:
                    matching_paths.append(match)
                    print("{0}".format(match))


print("matching_paths {0}".format(matching_paths))

for matching_path in matching_paths:
    match_basename = path.basename(match)
    if match_basename == cwd_basename:
        print("Skipping {9}".format(match_basename))
    else:
        pass
        
        

#
#
# matches=$( echo $python_script | python3 - )
#
# for match in $matches
# do
#   echo "XXX${match}XXX"
# done
#
# exit 0
# #echo $matches
#
# current_dir_basename=$(basename $PWD)
# #echo "current_dir_basename $current_dir_basename"
#
# for match in $matches
# do
#   match_basename=$(basename $match)
#   #echo "match_basename $match_basename"
#   if [ "$match_basename" == "$current_dir_basename"  ]; then
#     echo "Skipping $match"
#   else
#     if [ -f $match ] || [ -d $match ]; then
#       echo "Deleting $match"
#       rm -rf $match
#     fi
#   fi
# done
#
