#!/usr/bin/env ruby

total_characters = (ARGV[0] || '8').to_i


def random_num(length=10)
  chars = '0123456789'
  result = ''
  length.times { result << chars[rand(chars.size)] }
  result
end

puts random_num(total_characters)