#!/usr/bin/env ruby

major_minor = `ruby_version major_minor`.strip.chomp
if major_minor == '1.8'
  require "rbconfig" 
  rubylib =  "#{Config::CONFIG['prefix']}/lib/ruby"
  exec "${X_EDITOR} #{rubylib}"
elsif major_minor == '1.9'
  puts RbConfig::CONFIG['prefix']
  rubylib =  "#{RbConfig::CONFIG['prefix']}/lib/ruby"
  exec "${X_EDITOR} #{rubylib}"
end
