#!/bin/bash

outfile=/Users/tracy/Temp/sendmailout.tmp
echo yyy Sendmail args "$*" >$outfile

linecount=0
while [ "1" == "1" ]
do
	read line
	readstatus=$?
	echo Input line is $line >>$outfile
	if [ "$readstatus" != "0" ]
	then
		echo EOF detected. Leaving ... >>$outfile
		break
	fi
	arg1=`echo $line | awk '{print $1}'`
	if [ "$arg1" == "To:" ]
	then
		toAddress=`echo $line | awk '{print $2}'`
		echo "To: " $toAddress >>$outfile
		
	elif [ "$arg1" = "Subject:" ]
	then
		subject=`echo $line | awk '{print $2,$3,$4,$5,$6,$7,$8,$9}'`
		echo "Subject: " $subject >>$outfile
	fi
done
chmod 777 $outfile
 
  