#!/usr/bin/env bash

git stash save "Automatic temporary local cleanup "
current_branch=`get_active_git_branch`
git checkout master
git pull --rebase origin master
git checkout $current_branch
git pull --rebase origin master
git stash apply
git stash drop
