#!/usr/bin/env bash

if [ "$1" == "" ]; then
	exit 1
fi

tmp_dir=${HOME}/tmp

file_path=$1

file_name=$(file_parts $file_path | cut -d',' -f3)

cp $file_path $tmp_dir

pushd $tmp_dir >/dev/null

target_dir=$(file_parts $file_path | cut -d',' -f4)
mkdir -p $target_dir
unzip $file_name -d $target_dir

echo "Unpacked to $tmp_dir/$target_dir"

popd >/dev/null
