#!/bin/sh

fileToFind=$1

if [ X$1 == X ]
then
	exit 1
fi

searchDirs=`echo $PATH | sed s/:/\ /g`
for searchDir in $searchDirs
do
	if [ -f $searchDir/$fileToFind ]
	then
		echo $searchDir/$fileToFind
		break
	fi
done 

exit 0